# App Platform deployment spec
# Deploy with: doctl apps create --spec .do/app.yaml

name: crimeboard
region: nyc

services:
  - name: web
    github:
      repo: YOUR_GITHUB_USERNAME/crimeboard_ocean
      branch: main
      deploy_on_push: true
    source_dir: apps/web
    build_command: npm install && npm run build
    run_command: npm start
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        value: nyc3
      - key: SPACES_BUCKET
        value: crimeboard-evidence
      - key: SPACES_ENDPOINT
        value: https://nyc3.digitaloceanspaces.com
      - key: GRADIENT_AGENT_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: GRADIENT_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FUNCTIONS_BASE_URL
        scope: RUN_TIME
        type: SECRET
